import{NextResponse}from"next/server";import{z}from"zod";import{getAdminSession}from"@/lib/auth";import{sql}from"@/lib/db";import{getAdminProducts}from"@/lib/store";
const images=z.array(z.string().url()).max(6).default([]);
const schema=z.object({name:z.string().min(2).max(120),category:z.string().min(2).max(80),description:z.string().min(5).max(2000),price:z.coerce.number().nonnegative(),salePrice:z.coerce.number().nonnegative().optional().or(z.literal("")),stock:z.coerce.number().int().min(0).max(100000),featured:z.boolean().default(false),images:images.optional(),image:z.string().url().optional().or(z.literal(""))});
const edit=z.object({id:z.string().uuid(),name:z.string().min(2).max(120),category:z.string().min(2).max(80),description:z.string().min(5).max(2000),price:z.coerce.number().nonnegative(),salePrice:z.coerce.number().nonnegative().optional().or(z.literal("")),stock:z.coerce.number().int().min(0).max(100000),featured:z.boolean(),images:images.optional(),image:z.string().url().optional().or(z.literal(""))});
function slugify(x:string){return x.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
const list=async()=>getAdminProducts();
export async function GET(){if(!await getAdminSession())return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json(await list())}
export async function POST(req:Request){if(!await getAdminSession())return NextResponse.json({error:"Unauthorized"},{status:401});try{const p=schema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Check the product fields."},{status:400});const x=p.data,slug=slugify(x.name)+"-"+Date.now().toString(36),productImages=x.images?.length?x.images:x.image?[x.image]:["https://placehold.co/900x1125/F0ECE5/171513?text=NIMA"];const rows=await sql.query("INSERT INTO products(name,slug,category,description,price,sale_price,stock,images,featured,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,true) RETURNING id,name,slug,category,description,price,sale_price,stock,images,featured,active",[x.name,slug,x.category,x.description,x.price,x.salePrice===""?null:x.salePrice??null,x.stock,JSON.stringify(productImages),x.featured]);return NextResponse.json(rows[0])}catch{return NextResponse.json({error:"Could not create product."},{status:500})}}
export async function PUT(req:Request){if(!await getAdminSession())return NextResponse.json({error:"Unauthorized"},{status:401});try{const p=edit.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Check the product fields."},{status:400});const x=p.data;const hasImages=Array.isArray(x.images);const imageValue=hasImages?JSON.stringify(x.images):x.image?JSON.stringify([x.image]):"";const rows=await sql.query("UPDATE products SET name=$1,category=$2,description=$3,price=$4,sale_price=$5,stock=$6,featured=$7,images=CASE WHEN $8='' THEN images ELSE $8::jsonb END,updated_at=now() WHERE id=$9 RETURNING id,name,slug,category,description,price,sale_price,stock,images,featured,active",[x.name,x.category,x.description,x.price,x.salePrice===""?null:x.salePrice??null,x.stock,x.featured,imageValue,x.id]);if(!rows[0])return NextResponse.json({error:"Product not found."},{status:404});return NextResponse.json(rows[0])}catch{return NextResponse.json({error:"Could not update product."},{status:500})}}
export async function DELETE(req:Request){if(!await getAdminSession())return NextResponse.json({error:"Unauthorized"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id"},{status:400});await sql.query("UPDATE products SET active=false,updated_at=now() WHERE id=$1",[id]);return NextResponse.json({ok:true})}