"use client";
import{useEffect,useState}from"react";import{ArrowRight,LogOut,MessageCircle,PackageSearch}from"lucide-react";
type Order={id:string;order_number:string;customer_name:string;subtotal:string|number;delivery_fee:string|number;total:string|number;status:string;items:any[];created_at:string};
const money=(n:string|number)=>"₦"+Number(n).toLocaleString();
function statusLabel(s:string){return s.replace("_"," ")}
export function OrderHistory(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState({orderNumber:"",phone:""}),[openTicket,setOpenTicket]=useState<string|null>(null),[ticket,setTicket]=useState({category:"order_support",message:""});
 useEffect(()=>{fetch("/api/orders/history").then(async r=>{const d=await r.json();if(r.ok){setOrders(d.orders||[]);setVerified(true)}}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 async function lookup(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/orders/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not verify your order.");setOrders(d.orders||[]);setVerified(true)}catch(e){setMessage(e instanceof Error?e.message:"Could not verify your order.")}finally{setBusy(false)}}
 async function submitTicket(orderNumber:string){setBusy(true);setMessage("");try{const r=await fetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...ticket,orderNumber})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create support ticket.");setOpenTicket(null);setTicket({category:"order_support",message:""});setMessage("Support ticket "+d.ticketNumber+" has been created.");}catch(e){setMessage(e instanceof Error?e.message:"Could not create support ticket.")}finally{setBusy(false)}}
 async function signOut(){await fetch("/api/orders/logout",{method:"POST"});setOrders([]);setVerified(false)}
 if(loading)return <div className="history-loading card">Checking for a saved order session...</div>;
 if(!verified)return <div className="history-verify card"><div className="eyebrow">Order history</div><h2>Find your orders.</h2><p>Enter an order reference and the phone number used at checkout. One verified order unlocks your recent order history on this browser.</p><form className="history-form" onSubmit={lookup}><div className="field"><label>Order reference</label><input required value={form.orderNumber} onChange={e=>setForm({...form,orderNumber:e.target.value})} placeholder="NIMA-XXXXXXXXXXXX"/></div><div className="field"><label>Phone number</label><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="080..."/></div>{message&&<div className="site-notice" role="alert"><strong>NIMA.</strong><span>{message}</span></div>}<button className="btn" disabled={busy}>{busy?"Verifying...":"View order history"} <ArrowRight size={16}/></button></form></div>;
 return <div className="history-shell">{message&&<div className="site-notice history-notice" role="status"><strong>NIMA.</strong><span>{message}</span></div>}<div className="history-head"><div><div className="eyebrow">Order history</div><h2>Your NIMA orders.</h2></div><button className="btn secondary" onClick={signOut}><LogOut size={15}/> Sign out</button></div><div className="history-list">{orders.map(order=><article className="history-order card" key={order.id}><div className="history-order-head"><div><div className="history-ref">{order.order_number}</div><div className="history-date">{new Date(order.created_at).toLocaleDateString()}</div></div><span className={"order-status order-status-"+order.status}>{statusLabel(order.status)}</span></div><div className="history-items">{(Array.isArray(order.items)?order.items:[]).map((item:any,i:number)=><div key={item.productId||i}><span>{item.quantity} × {item.name}</span><strong>{money(Number(item.price)*Number(item.quantity))}</strong></div>)}</div><div className="history-total"><span>Total</span><strong>{money(order.total)}</strong></div><button className="support-trigger" onClick={()=>setOpenTicket(openTicket===order.order_number?null:order.order_number)}><MessageCircle size={15}/> Get help with this order</button>{openTicket===order.order_number&&<div className="ticket-form"><div className="field"><label>What do you need help with?</label><select value={ticket.category} onChange={e=>setTicket({...ticket,category:e.target.value})}><option value="order_support">Order support</option><option value="delivery">Delivery</option><option value="product">Product question</option><option value="return_refund">Return / refund</option></select></div><div className="field"><label>Message</label><textarea required rows={4} value={ticket.message} onChange={e=>setTicket({...ticket,message:e.target.value})} placeholder="Tell NIMA what happened..."/></div><button className="btn" disabled={busy} onClick={()=>submitTicket(order.order_number)}>{busy?"Sending...":"Create support ticket"}</button></div>}</article>)}</div></div>
}